{
    'name': 'Construction specific',
    'version': '10.0',
    'author': 'Acysos S.L.',
    'category': 'Specific',
    "contributors": ['Ignacio Ibeas ignacio@acysos.com', 'Alexander Ezquevo alexander@acysos.com', ],
    'website': 'http://www.acysos.com',
    'images': [],
    'depends': ['stock_account',
                'product',
                'sale_stock',
                'hr_timesheet_sheet',
                'procurement',
                'hr_expense',
                'project_task_material',
                'hr_holidays',
                'hr_worked_days_activity',
                'hr_worked_days_from_timesheet',
                'hr_worked_days_hourly_rate',
                'hr_worked_days_hourly_rate_timesheet',
                'hr_timesheet_task'],
    'data': ['views/sale_order_view.xml',
             'views/product_view.xml',
             'views/project_task_materials.xml',
             'views/res_company_view.xml',
             'views/project_view.xml',
             'views/hr_holidays_view.xml',],
    'images': ['static/description/banner.jpg'],
    'installable': True,
    'auto_install': False,
}
