{
    'name': 'Construction specific',
    'version': '1.0',
    'author': 'Acysos S.L.',
    'category': 'Specific',
    'description': """
Custom code for Construction
    """,
    'website': 'http://www.acysos.com',
    'images': [],
    'depends': ['sale',
                'sale_layout',
                'stock_account',
                'product',
                'sale_stock',
                'hr_timesheet_sheet',
                'sale_service',
                'sale_order_project',
                'procurement',
                'timesheet_task',
                'purchase_order_precreate_analytic',
                'hr_expense',
                'project_task_materials',
                'project_task_materials_stock',
                'stock_valued',
                'hr_holidays',
                'l10n_es_partner',
                'hr_timesheet_invoice',
                'hr_worked_days_activity',
                'hr_worked_days_from_timesheet',
                'hr_worked_days_hourly_rate',
                'hr_worked_days_hourly_rate_timesheet',
                'hr_timesheet_task',
                'mail'],
    'data': ['views/sale_order_view.xml',
             'views/product_view.xml',
             'views/hr_timesheet_sheet_view.xml',
             'views/project_task_materials.xml',
             'views/res_company_view.xml',
             'views/project_task_view.xml',
             'views/project_view.xml',
             'views/stock_picking_view.xml',
             'views/purchase_order_view.xml',
             'views/hr_holidays_view.xml',
             'views/hr_timesheet_view.xml',
             'views/mail_compose_message_view.xml',
             'views/analytic_view.xml'],
    'js': [],
    'qweb': [],
    'css': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
}
