from . import sale
from . import partner
from . import hr_timesheet_sheet
from . import hr_timesheet_line
from . import procurement
from . import project_task_materials
from . import res_company
from . import sale_order
from . import purchase_order
from . import stock
from . import hr_expense
from . import project
from . import hr_timesheet
from . import hr_holidays
from . import analytic
from . import project_project
